name = "compliance/smart_meter"
version = "0.1.0"
license = "Apache-2.0"

description = "Aiken contract suite for Compliance Smart Meter."

[project]
source-dir = "aiken_contracts"
script-dir = "plutus_scripts"
build-dir  = "build"
check-format = true

dependencies = []

[tests]
test-dir = "aiken_contracts/tests"