name = "compliance_smart_meter"
version = "0.1.0"
license = "Apache-2.0"

"Aiken contract suite for Compliance Smart Meter."

[project]
source-dir = "cardano/aiken_contracts"   # Where .ak files live
script-dir = "cardano/plutus_scripts"    # Where compiled Plutus scripts go
build-dir = "cardano/build"              # Build artifacts
check-format = true                      # Auto format on build

[dependencies]
# We will add later if we use external libs

[tests]
test-dir = "cardano/aiken_contracts/tests"   # Optional test directory