name = "compliance/smart_meter"
version = "0.1.0"
license = "Apache-2.0"

description = "Aiken contract suite for Compliance Smart Meter."

[project]
source-dir = "cardano/aiken_contracts"
script-dir = "cardano/plutus_scripts"
build-dir = "cardano/build"
check-format = true

[dependencies]
# Add later if external Aiken packages are needed

[tests]
test-dir = "cardano/aiken_contracts/tests"
